### ISSUE TITLE
linux compatibility

### ISSUE THREAD

**Issue by viniciussanchez** [JoseJimeniz/scrypt-for-delphi#2]
works perfectly on windows. but on linux it doesn't work because it has native windows class dependencies

**Comment by viniciussanchez** [comment]
**UnicodeFromLocaleChars** is a wrapper for the **MultiByteToWideChar** function.
http://docwiki.embarcadero.com/Libraries/Rio/en/System.UnicodeFromLocaleChars

**Comment by viniciussanchez** [comment]
![image](https://user-images.githubusercontent.com/16382981/74341047-d9e6eb80-4d85-11ea-9f26-baf246b3338c.png)

**Comment by viniciussanchez** [comment]
QueryPerformanceCounter > TStopWatch (Cross platform)
https://medium.com/@viniciuss.sanchez/diagnostico-de-performance-usando-tstopwatch-e-ttimespan-ed13c21311af

**Comment by viniciussanchez** [comment]
**CoCreateGUID** to **CreateGUID** 
http://docs.embarcadero.com/products/rad_studio/delphiAndcpp2009/HelpUpdate2/EN/html/delphivclwin32/SysUtils_CreateGUID.html
Note: Under Windows, CreateGUID calls the Windows API CoCreateGUID.
Note: Under Linux, CreateGUID calls uuid_generate_time.

**Comment by JackTrapper** [comment]
Don't forget; it also has to work in Delphi 5!
